spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: qwerty

server:
  port: 8085